# Generated by Django 3.2.14 on 2022-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Houseid', models.CharField(max_length=200, verbose_name='Уникальный идентификатор записи дома')),
                ('Houseguid', models.CharField(max_length=200, verbose_name='Глобальный уникальный идентификатор дома')),
                ('Fias_update_date', models.DateTimeField(verbose_name='Дата внесения (обновления) записи')),
                ('Is_actual', models.BooleanField(verbose_name='Актуальность')),
                ('Duplicate', models.CharField(blank=True, max_length=200, verbose_name='Если поле заполнелно то является дублем')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
